name: Run Postman API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run "Postman Collections/Zippo.json" --reporters cli,junit --reporter-junit-export results.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-report
          path: results.xml
